### ISSUE TITLE
Run metapopulation installer needs a mode where clean up happens, but not initial population is imported.

### ISSUE THREAD

**Issue by jpwijbenga** [AmpersandTarski/prototype#100]
Run metapopulation installer needs a mode where clean up happens, but not initial population is imported.
Such that environments that were edited are cleaned up but not reset of their edits.
this is about ' /api/v1/installer/metapopulation '

**Comment by hanjoosten** [comment]
Unfortunately, then we need to know what was changed. The model only knows the current state. So I don't see how this would be feasable. If you have ideas, please post them here

**Comment by Michiel-s** [comment]
Added a new admin API `GET /api/v1/admin/installer/metapopulation/cleanup`. This will inspect the generated Ampersand model file interfaces.json and deletes every `PF_Interface` atom from the database that does not occur in the model file.

This will then prevent the warning `"Interface id '{$ifcAtom->getId()}' specified as accessible interface, but this interface is not defined. Run meta population installer to delete those interfaces"` from being reported in the logs.
