### ISSUE TITLE
ConceptNotFoundException not found, Exception :).

### ISSUE THREAD

**Issue by jpwijbenga** [AmpersandTarski/prototype#115]
![image](https://github.com/AmpersandTarski/prototype/assets/6123882/fe268058-07de-4971-b3b1-133cf23550aa)

**Comment by hanjoosten** [comment]
???

**Comment by Michiel-s** [comment]
I talked about this with @jpwijbenga. The filename of the Exception class does not follow the convention of being the same as the class name. Therefore the class cannot be found.

You get a ConceptNotFound class not found error.

This is a bug.
