### ISSUE TITLE
Update functionality in the front end

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/prototype#150]
**Is your feature request related to a problem? Please describe.**
This issue is about the look and feel of a univalent relation (aka an attribute) in the user interface.
Here is a small example:
```Ampersand
CONTEXT Issue

RELATION r[A*B]
    = [("A1", "B1")]

INTERFACE Try : "_SESSION"[SESSION] BOX
  [ "" : V[SESSION*A] BOX<TABLE>
     [ "A" : I
     , "B" : r[A*B]   CRUD
     ]
  ]

ENDCONTEXT
```
Here is the corresponding interface:
![afbeelding](https://github.com/AmpersandTarski/prototype/assets/275768/69859016-f44c-4523-b54b-351f259aedca)

The specification says I can update the field. However, the screen does not suggest that it is updatable. I must first bring my mouse to the field to discover that I can remove the attribute from field B, and only then I get a window in which I can introduce the new value.

**Describe the solution you'd like**
I would like to see this instead:
![afbeelding](https://github.com/AmpersandTarski/prototype/assets/275768/846e1141-a9ca-432c-845f-e56ca394152f)
This suggests much better that the field can be edited. I can start editing without any click.

I suggest changing the interface for univalent relations. It can be made to look more like the interface for non-univalent relations.

**Comment by stefjoosten** [comment]
The solution is to add a line to this script:
```Ampersand
REPRESENT B TYPE ALPHANUMERIC
```

**Comment by hanjoosten** [comment]
The problem was that initially, concept `B` did not have a representation, so it is an object, not a scalar. Objects cannot be editable by themselves. So telling Ampersand that `B` is a scalar, represented by an `ALPHANUMERIC`, does the job.
