### ISSUE TITLE
In prototype backend adapt ProtoContext.php

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/prototype#156]

**Comment by Michiel-s** [comment]
### concept.json
- [ ] defaultViewId -> defaultViewName
- [ ] id -> name

### conjuncts.json
No changes

### interfaces.json
- [ ] id -> name
- [ ] ifcObejct.expr.srcConceptId -> ifcObject.expr.srcConceptName
- [ ] ifcObejct.expr.tgtConceptId -> ifcObject.expr.tgtConceptName
- [ ] ifcObject.id -> ifcObject.name
- [ ] ifcObject.viewId -> ifcObject.viewName
- [ ] ...refSubInterfaceId -> ...refSubInterfaceName

### populations.json
No changes

### relations.json
- [ ] srcConceptId -> srcConceptName
- [ ] tgtCocneptId -> tgtConceptName

### roles.json
- [ ] removed `id`
- [ ] added `label`
- [ ] added `isService` boolean

Note! the `maintains` list refers to rules names...

### rules.json
- [ ] srcConceptId -> srcConceptName
- [ ] tgtCocneptId -> tgtConceptName
- [ ] added `label`

### settings.json
No changes

### views.json
- [ ] conceptId -> conceptName
- [ ] added `name` (to replace `label`)
- [ ] added `label`

**Comment by Michiel-s** [comment]
Part of https://github.com/AmpersandTarski/prototype/pull/166
