### ISSUE TITLE
Unknown 'tableOf' option for relation 'isaCopy[Concept*Concept]

### ISSUE THREAD

**Issue by sefanja** [AmpersandTarski/prototype#212]
# What happened
Error message: "Invalid exec engine function call as defined in Concepts.adl:46:5. Function call 'TransitiveClosure(isa[Concept*Concept],Concept,isaCopy[Concept*Concept],isaPlus)'. Unknown 'tableOf' option for relation 'isaCopy[Concept*Concept]'"

# What I expected
No error message.

# Version of ampersand that was used
22 November 2024

# Steps to reproduce
1. Insert source script at rap.cs.ou.nl
2. Press Compile

# Source of ampersand script
CONTEXT X
CONCEPT A MEANING {+ none +}
CONCEPT B MEANING {+ none +}
CLASSIFY A ISA B
ENDCONTEXT

**Comment by hanjoosten** [comment]
Thanks for reporting. This is the same issue as https://github.com/AmpersandTarski/prototype/issues/210. But now we have a tiny reproducer.

**Comment by stefjoosten** [comment]
It has been fixed in issue #210.

**Comment by Michiel-s** [comment]
Please note that the fix is applied in main branch by #214, but also applied on v1 and released in [v1.18.1](https://github.com/AmpersandTarski/prototype/releases/tag/v1.18.1) and applied on v2 branch.

**Comment by stefjoosten** [comment]
I have redeployed RAP on rap.cs.ou.nl with version [v1.18.1](https://github.com/AmpersandTarski/prototype/releases/tag/v1.18.1) and verified that the script of @sefanja (see above) works.
