### ISSUE TITLE
Excel importer causes an unjustified error.

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/prototype#218]
# What happened
I uploaded an excel file, [Diensten.xlsx](https://github.com/user-attachments/files/18022658/Diensten.xlsx), in the Excel importer, with this result:
<img width="1407" alt="afbeelding" src="https://github.com/user-attachments/assets/24405be5-1380-4def-bb99-6d4e3b43894b">
I've spent approximately 2 days identifying the bug, but finally I managed to get it as small as this.

# What I expected
Importing this file should have no effect because it does not contain any tables. However, it causes an error: Concept '' is not defined.

I would like to see that this file yields no errors and is simply ignored, for not containing any tables.

# Version of the prototype framework
I used `ampersandtarski/prototype-framework:v1.18.0`. 

# Steps to reproduce

1. Run any prototype (I ran it with the APM-prototype)
2. Open the Excel importer
3. Select the file 'Diensten.xlsx'
4. Upload it.

**Comment by hanjoosten** [comment]
Did you do this same experiment with the main version of the prototype framework? It is well possible that it gives other results.

**Comment by stefjoosten** [comment]
# Analysis
I lost another half day on what is most likely the same error. This time I isolated the bug by producing two very small Excel files: [Fixed.xlsx](https://github.com/user-attachments/files/18209278/Fixed.xlsx) and [Issue.xlsx](https://github.com/user-attachments/files/18209279/Issue.xlsx). Open both files and they look quite similar from an Ampersand perspective.

They give the following behavior:
<img width="1120" alt="afbeelding" src="https://github.com/user-attachments/assets/501d2fbc-75e9-413d-9237-4e05de2cb40f" />

I could find only one difference: the tab's name in the spreadsheet is different from both files. Lo and behold: it looks like the name "Personen" on the tab allows me to switch: When I rename it to "Mensen", it works. When I rename it back to Personen, it fails again.


Then I made my Ampersand source file small:
```Ampersand
CONTEXT Issue  IN ENGLISH REST

RELATION naam [Persoon*Naam] [UNI]

ENDCONTEXT
```
Strangely enough, this too fixed the error:
<img width="1125" alt="afbeelding" src="https://github.com/user-attachments/assets/42830a2d-beab-44c3-bc90-2620d9917378" />

So, I still don't know the cause of this error, but it should be easier to diagnose with these symptoms.

**Comment by Michiel-s** [comment]
This is not a bug but a feature.

Please read this part of the documenation: https://ampersandtarski.github.io/ampersand/the-excel-importer#how-to-create-importable-excel-files

> There are 2 ways to import an Excel file. One is by using an appropriate INTERFACE definition (automatically detected based on sheet name equals INTERFACE name). The benefit of using this method is that you do not have to change your Excel files when you modify the names of relations in your amperand model. It is also more readable for third parties. The other is the (traditional) [import block] syntax.

**Comment by stefjoosten** [comment]
Reminder:
If the worksheet name matches an interface name and cell A1 on that worksheet uses enclosing square brackets, then the importer should give a message: "Worksheet <worksheet name> is parsed in the interface-method. see https://ampersandtarski.github.io/ampersand/the-excel-importer#how-to-create-importable-excel-files for more info."

@Michiel-s  will change the error message in the Angular prototype framework, not in version 1.18.1
