### ISSUE TITLE
Protection against SQL-injection

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/prototype#74]
Issue AmpersandTarski/Ampersand#271 claims that the generated web-application is not protected against SQL-injection.

Since the application is generated, an effective way to do this is to escape all input fields. The Ampersand-application should use ANSI-SQL all the way, so the (simple) ANSI escape mechanism is sufficient for this purpose: Simply encode all ' (single tick) characters with '' (two single ticks).
(see also https://www.owasp.org/index.php/SQL_Injection_Prevention_Cheat_Sheet)

**Comment by Michiel-s** [comment]
Our prototypes are protected against malicious user input. Everything is escaped. We can do better with SQL Prepared statements, but for now we're good.
