### ISSUE TITLE
build stops on  No match in record selector aavtxt

### ISSUE THREAD

**Issue by gedelaar** [AmpersandTarski/prototype#82]
https://github.com/gedelaar/pattern

when building the adl file 
docker compose up -d --build

It stops with next message
#11 0.449 2021-11-21 20:08:12.525337: [debug] Reading internal file Interfaces.ifc
#11 0.452 2021-11-21 20:08:12.527891: [debug] Reading internal file Navbar.adl
#11 0.462 2021-11-21 20:08:12.537514: [debug] Reading internal file Navbar.ifc
#11 0.465 2021-11-21 20:08:12.541008: [debug] Reading internal file Roles.adl
#11 0.470 2021-11-21 20:08:12.546516: [error] No match in record selector aavtxt
#11 0.471 ampersand: No match in record selector aavtxt
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c ampersand proto Main.adl   --proto-dir /var/www   --verbose]: exit code: 1

unfortunately I don't have a copy of the working code. So I'm stuck

**Comment by gedelaar** [comment]
Door in Register.adl bij RELATION ingangsdatum en bij RELATION einddatum, bij beide de [SUR] weg te halen, is het probleem opgelost. Althans, dan compileert deze weer zonder foutmelding.

**Comment by hanjoosten** [comment]
@gedelaar , Ik heb de oorzaak gevonden en er een issue van aangemaakt. Ik denk dat dit snel te verhelpen is.

**Comment by hanjoosten** [comment]
De echte foutmelding had moeten zijn:
~~~
PropertyRule for SUR einddatum[RegisterId*Datum] which is defined at /home/han/hanGit/pattern/Register.adl:54:9 error:
  There are 4 violations of RULE "SUR einddatum[RegisterId*Datum]":
    (1965-01-01, 1965-01-01)
    (1975-01-01, 1975-01-01)
    (1985-01-01, 1985-01-01)
    (2000-01-01, 2000-01-01)
PropertyRule for SUR ingangsdatum[RegisterId*Datum] which is defined at /home/han/hanGit/pattern/Register.adl:38:9 error:
  There are 3 violations of RULE "SUR ingangsdatum[RegisterId*Datum]":
    (1965-01-01, 1965-01-01)
    (1975-01-01, 1975-01-01)
    (1985-01-01, 1985-01-01)
PropertyRule for TOT register[Inschrijving*Register] which is defined at /home/han/hanGit/pattern/Aantekening.adl:40:7 error:
  There are 3 violations of RULE "TOT register[Inschrijving*Register]":
    ("I001", "I001")
    ("I003", "I003")
    ("I002", "I002")
~~~

**Comment by Michiel-s** [comment]
@gedelaar, hoewel de Ampersand compiler weliswaar is bijgewerkt, is deze change nog niet automatisch verwerkt in de Docker image voor het prototype framework. Daar is ook nog een release voor nodig.

Ik zag in je [Dockerfile](https://github.com/gedelaar/pattern/blob/master/Dockerfile) ook dat je prototyep-framework v1.10.3 expliciet noemt. Die moet dan ook nog bijgewerkt worden, na de volgende release https://github.com/AmpersandTarski/prototype/releases
