### ISSUE TITLE
Error message needed for failure to connect to the database.

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/prototype#91]
# What happened
I made a [prototype](https://github.com/AmpersandTarski/Nutwente/commit/fa77022f71fd77538eaa7046fe441d302791f4d6), which builds correctly. However, the navbar isn't being loaded:
<img width="1044" alt="afbeelding" src="https://user-images.githubusercontent.com/275768/166913576-03af4e89-1fff-4824-801e-ac9bf480decd.png">

# What I expected
I expected the behaviour to be similar to the remote deployment, which shows:
<img width="1038" alt="afbeelding" src="https://user-images.githubusercontent.com/275768/166916138-f1ecd369-8570-4cfa-97b5-0bde0ae5e019.png">

# Version of ampersand that was used
The version information is found in the Dockerfile of the prototype. I'm using
```
FROM ampersandtarski/prototype-framework:v1.15.0
```

# Steps to reproduce

1. Clone github.com/AmpersandTarski/Nutwente/commit/fa77022f71fd77538eaa7046fe441d302791f4d6.
2. in the CLI (which is zsh on MacBook M1): docker compose up -d --build
3. in the browser (which is Firefox vs. 99.0.1): navigate to localhost

**Comment by Michiel-s** [comment]
Output in the frontend will now look like: 

![image](https://user-images.githubusercontent.com/7961582/182033033-a3f98268-42dc-4f41-a298-6ea1b8b1a783.png)
