### ISSUE TITLE
Excel import of population fails

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/prototype#96]
As I was working on AmpersandTarski/Nutwente, on commit @080d21b, I was able to run this prototype locally and log in. Then I tried to import some population...

# What happened?
I imported two Excel files successfully:
<img width="892" alt="afbeelding" src="https://user-images.githubusercontent.com/275768/167749897-af3f4fdf-13e4-4899-8a34-691b0c8c9420.png">
However, the database did not contain the population from these spreadsheets.
I checked the log to see what happened. 
```
prototype  | [2022-05-10 23:38:57] IO.INFO: Excel import started: parsing file /tmp/phpGd2v1B [] {"request_id":"8e6d4dbc67"}
prototype  | [2022-05-10 23:38:57] IO.NOTICE: No interface found with name as title of worksheet 'Intakegesprekken'. Parsing file without interface [] {"request_id":"8e6d4dbc67"}
prototype  | [2022-05-10 23:38:57] IO.INFO: Excel import completed [] {"request_id":"8e6d4dbc67"}
prototype  | [2022-05-10 23:38:57] EXECENGINE.INFO: ExecEngine started [] {"request_id":"8e6d4dbc67"}
prototype  | [2022-05-10 23:38:57] EXECENGINE.INFO: ExecEngine run #1585951724-1 (auto rerun: true) [] {"request_id":"8e6d4dbc67"}
prototype  | [2022-05-10 23:38:57] EXECENGINE.DEBUG: Select exec engine '{ExecEngine}' [] {"request_id":"8e6d4dbc67"}
prototype  | [2022-05-10 23:38:57] EXECENGINE.DEBUG: Exec engine run finished [] {"request_id":"8e6d4dbc67"}
prototype  | [2022-05-10 23:38:57] EXECENGINE.INFO: ExecEngine finished [] {"request_id":"8e6d4dbc67"}
prototype  | [2022-05-10 23:38:57] TRANSACTION.INFO: Request to close transaction: 1585951724 [] {"request_id":"8e6d4dbc67"}
prototype  | [2022-05-10 23:38:57] TRANSACTION.INFO: Checking invariant rules [] {"request_id":"8e6d4dbc67"}
prototype  | [2022-05-10 23:38:57] TRANSACTION.INFO: Commit transaction: 1585951724 [] {"request_id":"8e6d4dbc67"}
prototype  | [2022-05-10 23:38:57] APPLICATION.NOTICE: Imported Intakegesprekken.xlsx successfully [] {"request_id":"8e6d4dbc67"}
```
Does the back-end require an interface to read Excel sheets? Anyway, in spite of the absence of this interface and in spite of not having imported any population, the prototype signals a successful import of the spreadsheet. Yet, its population has not been loaded.

# Version of Ampersand that was used
I used the image ampersandtarski/prototype-framework:main[6d8a90b50], which uses Ampersand-v4.6.2 [51c3de2e65c540ef026925fe8547c991765a5588:refs/tags/v4.6.2]

**Comment by stefjoosten** [comment]
Stupid mistake of mine...

**Comment by Michiel-s** [comment]
@stefjoosten in response to your question: does the excel importer require an interface? No, but you can use one if you want.

A regular import sheet parses population blocks starting with `[block]` annotation in first column. That row contains relation names, the next row contains the target concepts and following rows  the population.

If you however match the sheet name with an existing interface name, that whole sheet is parsed using the labels of the interface. No special block notation needed. Just a single header row with the first level interface labels.
