### ISSUE TITLE
Date error in (Runtime) Excel importer

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/prototype#97]
Importing the date 00/01/1900 from Excel does not work properly.
Note that in Excel, `VALUE(00/01/1900)=0` (or if you format 0 as a date, you get 00/01/1900).
# What happened?
I have an Excel file with the following information:

![afbeelding](https://user-images.githubusercontent.com/275768/168074275-c28c1aa3-d254-4883-81a5-4ba96a13cac1.png)
I'm running the following script as a prototype:

```Ampersand
CONTEXT Issue97
   REPRESENT Datum TYPE DATETIME
   RELATION notifDate[Notification*Datum]
ENDCONTEXT
```

Then I use the Excel-importer to add population to the database:

<img width="1055" alt="afbeelding" src="https://user-images.githubusercontent.com/275768/168164598-7228fdb0-67d1-44e3-8533-6fda609ace56.png">

The error message is not clear about the location of the mistake, but experimentation shows that the date 00/01/1900 is to blame.
# Situation without the problematic date
When I remove notification 1:

<img width="337" alt="afbeelding" src="https://user-images.githubusercontent.com/275768/168165051-66587ceb-9883-469e-be24-f9fcf919118c.png">

I get a successful import:

<img width="950" alt="afbeelding" src="https://user-images.githubusercontent.com/275768/168165458-546a3191-0117-41ae-8d30-7605ae780bca.png">

and the database contains the correct data:

<img width="690" alt="afbeelding" src="https://user-images.githubusercontent.com/275768/168165831-097843c2-412a-40ac-b7f9-d9b68d07be52.png">

# Workaround: INCLUDE the Excel file
If I include the Excel file in the source code, like this:

```Ampersand
CONTEXT Issue97
INCLUDE "Issue.xlsx"
   REPRESENT Datum TYPE DATETIME
   RELATION notifDate[Notification*Datum]
ENDCONTEXT
```

everything works as expected. The database contents is:

![afbeelding](https://user-images.githubusercontent.com/275768/168073308-5484b1d1-9d86-41c5-b416-a0eec129e13c.png)

# Version of Ampersand that was used
I used the image ampersandtarski/prototype-framework:main[6d8a90b50], which uses Ampersand-v4.6.2 [51c3de2e65c540ef026925fe8547c991765a5588:refs/tags/v4.6.2]

**Comment by stefjoosten** [comment]
# Gravity of the bug
I spent hours trying to find the mistake in my spreadsheet, because the error message is absolutely not helpful. If it would have given me the file+worksheet+cell number, I would have found this much earlier.

# Solution
I think the correct solution is to allow any non-negative real number as a date, as defined in the ISO-standard. There is no reason to forbid it.

**Comment by hanjoosten** [comment]
We have two completely different implementations of reading an .xlsx file:
1) At Runtime (This one is used when you run the prototype and want to add population during the lifetime of your application). This implementation uses a PHP package. The code is PHP.
2) Statically (When compiling your ADL script to create a prototype, to add population to the initial database.) This implementation uses a Haskell library. The code is Haskell.

Both have been implemented separately, by different people. We assume they do more or less the same, but we know that it is likely that details of their behavior could differ, as an explicit specification of the behaviour does not exist. When differences submerge, there is no formal way to say which one is correct and which one is not. 

This said, it seems to me that @Michiel-s might be able to have a look at the runtime implementation to see if the required behaviour can be implemented.

**Comment by stefjoosten** [comment]
Hi @hanjoosten,
In this case, I would say that the "correct" way is to implement the ISO 8601 standard wrt dates as completely as we can. That is: without exceptions. Each exception that yields an error instead of the specified behavior gives agony to our users (and to ourselves). Presuming that Excel adheres to this standard, the signalled error would never occur.

**Comment by stefjoosten** [comment]
No excuse not to fix our own mistakes... :-)
What needs to be done:

- [ ] make error messages from the Excel importer point to the correct cell (instead of `position 0 (0)`), to facilitate locating bugs. (Partial workaround: use the compiler to import the excel sheet)
- [ ] interpret date 0 as 00/01/1900 (or 31/12/1899 for that matter) instead of a parse failure, to enable reading a larger category of Excel files.

**Comment by Michiel-s** [comment]
I'll diagnose the issue for the excel importer implementation in prototype framework.

First thing I'll definitely do is to let exceptions/errors specify the cell coordinate and sheet name. That is in full control of ourselves.

For working with spreadsheets we use a library. So maybe the issue with interpretation of dates is there. That I need to look into.

To be cont.

**Comment by Michiel-s** [comment]
I've updated the code so that cell location of error is shown, if applicable. The error would now have been:

![image](https://user-images.githubusercontent.com/7961582/182452109-82ca20bf-a369-436e-be2b-9a5ee09ffea6.png)
