### ISSUE TITLE
Piece of discussion: Domain-driven architecture in the frontend

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/prototype#99]
I came across this wonderful article about Domain-driven architecture in the frontend: [part 1](https://betterprogramming.pub/domain-driven-architecture-in-the-frontend-i-d27fb71b5cb0) and [part 2](https://betterprogramming.pub/domain-driven-architecture-in-the-frontend-ii-cdc46cf8ac1c).

I really love the clear separation of concerns and think it would allow us to create a more robust link between the Ampersand compiler and generated frontend code for prototypes. Especially to make it more easy to extend and customize for specific applications.

We are about to start to refactor the frontend framework (currently build with end-of-life [AngularJS framework](https://angularjs.org/)). Logical replacement frameworks are [React](https://reactjs.org/) or [Angular](https://angular.io/). I think it would be good to rethink what code we generate and how a frontend application can work with that. The article on domain-driven architecture very well suits our way of thinking with Ampersand; the domain model (ADL scripts) *drive* the database design, backend code, API specifications and frontend application.

Mapping Ampersand to the article:
* The Domain objects can come directly from Ampersand concepts and relations
* The Resources are defined by the way the backend framework is designed and provides the resource data according to the Ampersand interfaces
* The Use cases and Views can come directly from the Ampersand interfaces

![image](https://user-images.githubusercontent.com/7961582/179349007-0a9bf262-626e-408f-85ad-04d84fbebb49.png)

Minor note. In part 2 of the article Use cases are bundled in Services. I think it makes sense for us to first start with the Services only and have the UseCase::execute() logic directly in the methods of the service. Just to have less classes and files.

**Comment by Michiel-s** [comment]
@hanjoosten could you have a look at these two articles in prep of our working day next weekend? I interested in what you think. Would this be a feasible first step towards a new frontend implementation? Like the author says, it requires a lot of boiler plate code.. but hé, that we can generate by the Ampersand compiler right?

**Comment by Michiel-s** [comment]
I've updated the picture a little. For my own understanding and how I would explain the architecture myself

![Frontend domain-driven architecture](https://user-images.githubusercontent.com/7961582/179353036-c74803a6-e428-4e67-9830-1fc126f0bed6.jpg)

**Comment by hanjoosten** [comment]
The DDD approach is very logical. I suppose it is very well possible to generate a lot of this boilerplate by the ampersand generator. The easiest way to do so is by example. Plenty to talk about next saturday :)
